teku_container_command_extra_args:
  - --network=/network-config/config.yaml
  - --genesis-state=/network-config/genesis.ssz
  - --p2p-peer-upper-bound=100
  - --data-storage-non-canonical-blocks-enabled=true
  - --data-storage-mode=ARCHIVE
  - --logging=info
  - --Xlog-include-p2p-warnings-enabled
  - --metrics-block-timing-tracking-enabled
  - --ignore-weak-subjectivity-period-enabled
